services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/*/__pycache__
      - /app/*/*/__pycache__
    networks:
      - ai-assistant-network
    env_file:
      - .env
    command: uvicorn app.api.routes:app --host 0.0.0.0 --port 8000 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - ai-assistant-network  
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend 

networks:
  ai-assistant-network:
    driver: bridge 

